repos:
  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validar mensagem de commit
        entry: python validate_commit_msg.py
        language: system
        args: []
        stages: [commit-msg]