repos:
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validar mensagem de commit
        entry: python validate_commit_msg.py
        language: system
        args: []
        files: ^(COMMIT_EDITMSG)$