name: "Get Enviroment Pipeline"
description: "
      Esse step é responsável por pegar em qual branch está rodando
      a pipeline para que assim ele decida se vai dar deploy em dev ou prod
    "
inputs:
  CA_APP_BACKEND:
    description: ""
    required: false
    default: ""
  CA_APP_CONSUMER:
    description: "Override do nome do Container App Consumer"
    required: false
    default: ""
  CA_APP_FRONTEND:
    description: "Override do nome do Container App Frontend"
    required: false
    default: ""
  CA_APP_WORKER:
    description: "Override do nome do Container App Worker"
    required: false
    default: ""
  DOCKERFILE_BACKEND:
    description: "Override do caminho do Dockerfile Backend"
    required: false
    default: ""
  DOCKERFILE_CONSUMER:
    description: "Override do caminho do Dockerfile Consumer"
    required: false
    default: ""
  DOCKERFILE_WORKER:
    description: "Override do caminho do Dockerfile Worker"
    required: false
    default: ""
  DOCKERFILE_FRONTEND:
    description: "Override do caminho do Dockerfile Frontend"
    required: false
    default: ""
outputs:
  granto_env:
    description: Ambiente (Production ou Development)
    value: ${{ steps.set_env.outputs.granto_env }}
runs:
  using: composite
  steps:
    - name: Script Get Environment
      shell: bash
      id: set_env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "granto_env=Production" >> $GITHUB_OUTPUT
        else
          echo "granto_env=Development" >> $GITHUB_OUTPUT
        fi
    - name: Override de variáveis com inputs do chamador
      shell: bash
      run: |
        declare -A overrides=(
          ["CA_APP_BACKEND"]="${{ inputs.CA_APP_BACKEND }}"
          ["CA_APP_CONSUMER"]="${{ inputs.CA_APP_CONSUMER }}"
          ["CA_APP_FRONTEND"]="${{ inputs.CA_APP_FRONTEND }}"
          ["CA_APP_WORKER"]="${{ inputs.CA_APP_WORKER }}"
          ["DOCKERFILE_BACKEND"]="${{ inputs.DOCKERFILE_BACKEND }}"
          ["DOCKERFILE_CONSUMER"]="${{ inputs.DOCKERFILE_CONSUMER }}"
          ["DOCKERFILE_WORKER"]="${{ inputs.DOCKERFILE_WORKER }}"
          ["DOCKERFILE_FRONTEND"]="${{ inputs.DOCKERFILE_FRONTEND }}"
        )

        for var in "${!overrides[@]}"; do
          value="${overrides[$var]}"
          if [ -n "$value" ]; then
            echo "$var=$value" >> $GITHUB_ENV
            echo "Override: $var=$value"
          else
            echo "$var mantido do Key Vault"
          fi
        done
    
    - name: Print granto env
      shell: bash
      run: |
        [ -n "${{ inputs.CA_APP_BACKEND }}" ] && echo "CA_APP=${{ inputs.CA_APP_BACKEND }}"
        echo "Ambiente: $GRANTO"
      env:
        GRANTO: ${{ steps.set_env.outputs.granto_env }}
