name: "Get Enviroment Pipeline"
description: "
      Esse step é responsável por pegar em qual branch está rodando
      a pipeline para que assim ele decida se vai dar deploy em dev ou prod
    "
outputs:
  grant_env:
    description: Ambiente (Production ou Development)
    value: ${{ steps.set_env.outputs.granto_env }}
runs:
  using: composite
  steps:
    - name: Script Get Environment
      shell: bash
      id: set_env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "granto_env=Production" >> $GITHUB_OUTPUT
        else
          echo "granto_env=Development" >> $GITHUB_OUTPUT
        fi

    - name: Print granto env
      shell: bash
      run: |
        echo "Ambiente: $GRANTO"
      env:
        GRANTO: ${{ steps.set_env.outputs.granto_env }}
