name: "Versioning-staging"
description: "Executa o step de versionamento em Develop"
outputs:
  sha:
    description: Pega o 7 primeiros caracteres do commit
    value: ${{ steps.generate_tag.outputs.sha }}
runs:
  using: composite
  steps:
    - name: Run Versioning Stg
      shell: bash
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
