on:
  workflow_call:

  jobs:
    deploy:
        name: "Deploy"
        runs-on: ubuntu-latest
        needs: [versioning]
        if:  github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

        steps:
          - name: Run Deploy to APP
            run: echo "Deploy to APP v1.0.0"
    
    deploy-web:
        name: "Deploy Web"
        runs-on: ubuntu-latest
        needs: [versioning]
        if:  github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

        steps:
          - name: Run Deploy to APP
            run: echo "Deploy to APP v1.0.0"