name: Publish New Version Pipelines

on:
  push:
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"
    branches:
      - "feat/**"
      - "fix/**"
      - "test/**"
      - "refactor/**"
      - main
  pull_request:
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"
    types:
      - closed
    branches:
      - develop
      - master

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate-yml:
    name: "Validate YMLs CI Github"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: YML-lint
        id: yml-lint
        uses: ibiqlik/action-yamllint@v3

      - name: Output YML Log
        run: echo ${{ steps.yml-lint.outputs.logfile }}

      - name: Upload Log files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ymllint-file
          path: ${{ steps.yml-lint.outputs.logfile}}
          retention-days: 7

  versioning:
    name: "Versioning pipeline"
    runs-on: ubuntu-latest
    needs: [validate-yml]
    if: |
      github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
