on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: Run Checkout Branch
        run: |
          echo "Checkout Branch"
      
      - name: Run Build App
        uses: rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/build@develop

  tests:
      name: 'Tests'
      runs-on: ubuntu-latest
      needs: [build]

      steps:
        - name: Run Unit Tests
          run: |
            echo "Unit tests"
        
        - name: Run E2E Tests
          run: |
            echo "e2e tests"

        - name: Run Coverage
          run: |
            echo "Coverage"
    
  security-scan:
    needs: [tests]
    name: 'Security'
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy
        run: |
          echo "Trivy"

      - name: Run SonarQube
        run: |
          echo "SonarQube"
    
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: 'Code lint'
        uses: rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/lint@develop
    
  versioning-stg:
    name: 'Versioning-staging'
    runs-on: ubuntu-latest
    needs: [security-scan, lint]
    if: (github.event.pull_request.merged != true || github.event_name != 'pull_request') && (github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master')

    steps:
      - name: Run Generate tag
        uses: rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/versioning-stg@develop
        
  versioning:
    name: 'Versioning'
    runs-on: ubuntu-latest
    needs: [security-scan, lint]
    if: github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Run generate release
        uses: rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/versioning-prd@develop

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: [versioning]
    if:  github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Run Checkout Branch
        run: |
          echo "Checkout Branch"
      
      - name: "Deploy"
        uses: rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/deploy@develop
