on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: Run Checkout Branch
        run: |
          echo "Checkout Branch"
      
      - name: Run Build App
        uses: ./.github/actions/c-sharp/build

  tests:
    needs: [build]
    uses: ./.github/workflows/tests/tests.yml@develop
    
  security-scan:
    needs: [tests]
    uses: ./.github/workflows/security/security.yml@develop
    
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: 'Code lint'
        uses: ./.github/actions/c-sharp/lint
    
  versioning-stg:
    name: 'Versioning-staging'
    runs-on: ubuntu-latest
    needs: [security-scan, lint]
    if: (github.event.pull_request.merged != true || github.event_name != 'pull_request') && (github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master')

    steps:
      - name: Run Generate tag
        uses: ./.github/actions/c-sharp/versioning-stg
        
  versioning:
    name: 'Versioning'
    runs-on: ubuntu-latest
    needs: [security-scan, lint]
    if: github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: Run generate release
        uses: ./.github/actions/c-sharp/versioning-prd

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: [versioning]
    if:  github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Run Checkout Branch
        run: |
          echo "Checkout Branch"
      
      - name: "Deploy"
        uses: ./.github/actions/c-sharp/deploy
