on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: Run Checkout Branch
        run: |
          echo "Checkout Branch"
      
      - name: Run Build App
        run: |
          echo "Build App"

  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Run Unit Tests
        run: |
          echo "Unit tests"
      
      - name: Run E2E Tests
        run: |
          echo "e2e tests"

      - name: Run Coverage
        run: |
          echo "Coverage"
    
  security-scan:
    name: 'Vulnerability'
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Run Trivy
        run: |
          echo "Trivy"

      - name: Run SonarQube
        run: |
          echo "SonarQube"
    
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Run Lint
        run: |
          echo "Lint"
    
  versioning:
    name: 'Versioning Environment Development'
    runs-on: ubuntu-latest
    needs: [security-scan, lint]

    steps:
      - name: Run Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
    
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: [versioning]

    steps:
      - name: Run Deploy to APP
        env:
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          echo "Deploy to APP"
          echo $tag