on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Build App
        uses: |
          rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/build

  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
      - name: Tests
        uses: |
          rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/tests@main

  security-scan:
    needs: [tests]
    name: 'Security'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Security
        uses: |
          rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/security@main

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - name: 'Code lint'
        uses: |
          rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/lint@main

  versioning-stg:
    name: 'Versioning-staging'
    runs-on: ubuntu-latest
    needs: [security-scan, lint]
    if: |
      (github.event.pull_request.merged != true ||
      github.event_name != 'pull_request')
      && (github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master')

    steps:
      - uses: actions/checkout@v4
      - name: Run Generate tag
        uses: |
          rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/versioning-stg@main

  versioning:
    name: 'Versioning'
    runs-on: ubuntu-latest
    needs: [security-scan, lint]
    if: |
      github.event.pull_request.merged == true &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - uses: actions/checkout@v4
      - name: Run generate release
        uses: |
          rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/versioning-prd@main

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: [versioning]
    if: |
      github.event.pull_request.merged == true &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v4
      - name: "Deploy"
        uses: |
          rafaelrochasantos/poc-centralize-workflow/.github/actions/c-sharp/deploy@main
