on:
  workflow_call:

  jobs:
    tests:
        name: 'Tests'
        runs-on: ubuntu-latest
        needs: [build]

        steps:
          - name: Run Unit Tests
            run: |
              echo "Unit tests"
          
          - name: Run E2E Tests
            run: |
              echo "e2e tests"

          - name: Run Coverage
            run: |
              echo "Coverage"
    